CREATE TABLE LOJAS (
	CODIGO BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL,
	TIPO VARCHAR(50) NOT NULL,
	NOTA BIGINT(20) NOT NULL DEFAULT 5
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

INSERT INTO LOJA 
	(NOME, TIPO)
	VALUES ('GEARBEST', 'TECNOLOGIA')