CREATE TABLE LOJAS (
	CODIGO BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	CNPJ VARCHAR(19) NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	NOTA BIGINT(20) NOT NULL DEFAULT 5
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

INSERT INTO LOJAS (CNPJ, NOME) VALUES ('81.367.538/0001-30', 'GEARBEST');

CREATE TABLE CLIENTES (
    CODIGO BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    CPF VARCHAR(14) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    
	LOGRADOURO VARCHAR(50) NOT NULL,
	NUMERO VARCHAR(50) NOT NULL,
	COMPLEMENTO VARCHAR(50) NOT NULL,
	BAIRRO VARCHAR(50) NOT NULL,
	CEP VARCHAR(9) NOT NULL,
	CIDADE VARCHAR(50) NOT NULL,
	ESTADO VARCHAR(2) NOT NULL,
	
	CARTAO_CREDITO VARCHAR(20) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

INSERT INTO CLIENTES (
    CPF, 
    NOME,
    LOGRADOURO,
    NUMERO,
    COMPLEMENTO,
    BAIRRO,
    CEP,
    CIDADE,
    ESTADO,
    CARTAO_CREDITO
)VALUES ('622.136.554-64', 'Elias Raul Aragão', 'Travessa Topázio', 642, 'Casa', 'Centenário', '55030-225', 'Caruaru', 'PE', '5283 2031 8051 5659');

CREATE TABLE PRODUTOS (
    CODIGO BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    CATEGORIA VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(50) NOT NULL,
    ESTOQUE_UN INTEGER NOT NULL,
    PRECO NUMERIC NOT NULL,
	
	LOJA_ID BIGINT(20) NOT NULL,

	CONSTRAINT `fk_loja` FOREIGN KEY (LOJA_ID) REFERENCES LOJAS (CODIGO)

)ENGINE=InnoDB DEFAULT CHARSET=UTF8;


INSERT INTO PRODUTOS (
    CATEGORIA,
    DESCRICAO,
    ESTOQUE_UN,
    PRECO,
    LOJA_ID
)VALUES ('TECNOLOGIA', 'MI BAND 3', 100, 90.5, 1);

CREATE TABLE VENDAS(

    CODIGO BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    CLIENTE_ID BIGINT(20),
    DATA_VENDA DATE NOT NULL,
    PRECO_TOTAL NUMERIC,
    PARCELAS INTEGER,
    
    CONSTRAINT `fk_cliente` FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES (CODIGO)

)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

INSERT INTO VENDAS (
    CLIENTE_ID,
    DATA_VENDA,
    PRECO_TOTAL,
    PARCELAS
)VALUES (1, '2018-12-02', 150, 1);

CREATE TABLE PRODUTO_VENDA(
    CODIGO BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    PRODUTO_ID BIGINT(20) NOT NULL,
    QUANTIDADE INT NOT NULL,
    VENDA_ID BIGINT(20) NOT NULL,
    
    CONSTRAINT `fk_produto` FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTOS (CODIGO),
    CONSTRAINT `fk_venda` FOREIGN KEY (VENDA_ID) REFERENCES VENDAS (CODIGO)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

INSERT INTO PRODUTO_VENDA (
    PRODUTO_ID,
    QUANTIDADE,
    VENDA_ID
) VALUES (1, 20, 1);

CREATE TABLE CARRINHO(
    CODIGO BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    PRODUTO_ID BIGINT(20) NOT NULL,
    QUANTIDADE INT NOT NULL,
    CLIENTE_ID BIGINT(20) NOT NULL,
    
    CONSTRAINT `fk_produto_venda` FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTOS (CODIGO),
    CONSTRAINT `fk_cliente_venda` FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES (CODIGO)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

INSERT INTO CARRINHO (
    PRODUTO_ID,
    QUANTIDADE,
    CLIENTE_ID
) VALUES (1, 1, 1);