CREATE TABLE LOJAS (
	CODIGO BIGINT(20) PRIMARY KEY,
	CNPJ VARCHAR(19) NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	NOTA BIGINT(20) NOT NULL DEFAULT 5
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

INSERT INTO LOJAS (CNPJ, NOME, NOTA) VALUES ('81.367.538/0001-30', 'GEARBEST');

CREATE TABLE CLIENTES (
    CODIGO BIGINT(20) PRIMARY KEY,
    CPF BIGINT(14) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    
	LOGRADOURO VARCHAR(50) NOT NULL,
	NUMERO VARCHAR(50) NOT NULL,
	COMPLEMENTO VARCHAR(50) NOT NULL,
	BAIRRO VARCHAR(50) NOT NULL,
	CEP VARCHAR(50) NOT NULL,
	CIDADE VARCHAR(50) NOT NULL,
	ESTADO VARCHAR(2) NOT NULL,
	
	CARTAO_CREDITO VARCHAR(20) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

INSERT INTO CLIENTES (
    CPF, 
    NOME,
    LOGRADOURO,
    NUMERO,
    COMPLEMENTO,
    BAIRRO,
    CEP,
    CIDADE,
    ESTADO,
    CARTAO_CREDITO
)VALUES ('62213655464', 'Elias Raul Aragão', 'Travessa Topázio', 642, 'Casa', 'Centenário', Caruaru, PE, '5283 2031 8051 5659');

CREATE TABLE PRODUTOS (
    CODIGO BIGINT(20) PRIMARY KEY,
    CATEGORIA VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(50) NOT NULL,
    ESTOQUE_UN INTEGER NOT NULL,
    PRECO NUMBER NOT NULL,
    
    LOJA_ID BIGINT(20),
    FOREIGN KEY (LOJA_ID) REFERENCES LOJAS (CODIGO) 

)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

INSERT INTO PRODUTOS (
    CATEGORIA,
    DESCRICAO,
    ESTOQUE_UN,
    PRECO,
    LOJA_ID
)VALUES ('TECNOLOGIA', 'MI BAND 3', 100, 90.5, 1);

CREATE TABLE VENDA(

    CODIGO BIGINT(20) PRIMARY KEY,
    LOJA_ID BIGINT(20),
    CLIENTE_ID BIGINT(20),
    DATA_VENDA DATE NOT NULL,
    
    FOREIGN KEY (LOJA_ID) REFERENCES LOJAS (CODIGO),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (CODIGO)

);

INSERT INTO VENDA (
    LOJA_ID
    CLIENTE_ID
    DATA_VENDA
)VALUES (1, 1, 02/12/2018);

CREATE TABLE PRODUTO_VENDA(
    CODIGO BIGINT(20) PRIMARY KEY,
    PRODUTO_ID BIGINT(20) NOT NULL,
    QUANTIDADE INT NOT NULL,
    VENDA_ID BIGINT(20) NOT NULL,
    
    FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTOS (CODIGO),
    FOREIGN KEY (VENDA_ID) REFERENCES VENDA (CODIGO)
);

INSERTO INTO PRODUTO_VENDA (
    PRODUTO_ID,
    QUANTIDADE,
    VENDA_ID,
) VALUES (1, 20, 1);